# Generated by Django 5.2.3 on 2025-06-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aUTH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=10),
        ),
    ]
